# replicaCount: 1

# image:
#   repository: n8nio/n8n
#   tag: latest
#   pullPolicy: IfNotPresent

# service:
#   port: 5678

# resources:
#   requests:
#     cpu: "500m"
#     memory: "1Gi"
#   limits:
#     cpu: "1"
#     memory: "2Gi"

# persistence:
#   enabled: true
#   size: 10Gi

# ingress:
#   enabled: true
#   className: gce
#   host: n8n.variphi.com

# nodePool:
#   name: gke-prod-asia-south1-np-app-prod

replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/variphi/n8n/n8n-custom
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  port: 5678

env:
  - name: N8N_CUSTOM_EXTENSIONS
    value: /home/node/n8n-custom-nodes
  - name: NODE_ENV
    value: production

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

persistence:
  enabled: true
  size: 10Gi

ingress:
  enabled: true
  className: gce
  host: n8n.variphi.com

nodePool:
  name: gke-prod-asia-south1-np-app-prod
