-replicaCount: 1

image:
  repository: ""        # CI/CD isko --set se override karega
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5678

# ðŸ”¹ Ingress configuration (IMPORTANT FIX)
ingress:
  enabled: true
  host: n8n.variphi.com
  className: nginx        # agar GKE Ingress use kar rahe ho to remove bhi kar sakti ho
  annotations: {}
  tls: false              # TLS baad me enable kar sakte ho

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

env:
  N8N_HOST: "0.0.0.0"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "http"
  NODE_ENV: "production"
  GENERIC_TIMEZONE: "Asia/Kolkata"

persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce